# ──────────────────────────────────────────────────────────────
# AVID‑FP Object Store – parameterised deployment
# Each node reads /etc/avid/config.yaml for all runtime knobs.
# ──────────────────────────────────────────────────────────────
version: "3.9"

services:
  # ---------- storage cluster ----------
  server1:
    build: .
    image: avid-fp-store:latest
    command: ["-config", "/etc/avid/config.yaml"]
    volumes:
      - store1:/data
      - ./configs/server1.yaml:/etc/avid/config.yaml:ro
    ports:
      - "50051:50051" # gRPC
      - "9102:9102" # Prometheus metrics
    networks: [store]

  server2:
    image: avid-fp-store:latest # reuse the image built above
    command: ["-config", "/etc/avid/config.yaml"]
    volumes:
      - store2:/data
      - ./configs/server2.yaml:/etc/avid/config.yaml:ro
    ports:
      - "50052:50052"
      - "9103:9103"
    networks: [store]

  server3:
    image: avid-fp-store:latest
    command: ["-config", "/etc/avid/config.yaml"]
    volumes:
      - store3:/data
      - ./configs/server3.yaml:/etc/avid/config.yaml:ro
    ports:
      - "50053:50053"
      - "9104:9104"
    networks: [store]

  server4:
    image: avid-fp-store:latest
    command: ["-config", "/etc/avid/config.yaml"]
    volumes:
      - store4:/data
      - ./configs/server4.yaml:/etc/avid/config.yaml:ro
    ports:
      - "50054:50054"
      - "9105:9105"
    networks: [store]

  server5:
    image: avid-fp-store:latest
    command: ["-config", "/etc/avid/config.yaml"]
    volumes:
      - store5:/data
      - ./configs/server5.yaml:/etc/avid/config.yaml:ro
    ports:
      - "50055:50055"
      - "9106:9106"
    networks: [store]

  server6:
    image: avid-fp-store:latest
    command: ["-config", "/etc/avid/server6.yaml"]
    volumes:
      - store6:/data
      - ./configs/server6.yaml:/etc/avid/server6.yaml:ro
    ports:
      - "50056:50056"
      - "9107:9107"
    networks: [store]

  # ---------- monitoring ----------
  prometheus:
    image: prom/prometheus:v2.52.0
    volumes:
      - ./deploy/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks: [store]
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.2.4
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "3000:3000"
    networks: [store]
    restart: unless-stopped

# ---------- shared network ----------
networks:
  store:
    driver: bridge

# ---------- per‑node data volumes ----------
volumes:
  store1: {}
  store2: {}
  store3: {}
  store4: {}
  store5: {}
  store6: {}
